// Mock parking data for Alyamamah University
// In the future, this will be replaced with real-time API data from car detection sensors

export const parkingZones = {
  leftWing: {
    id: "left-wing",
    name: "Main Screen - Left Wing",
    building: "Tuwaiq Building",
    totalSlots: 20,
  },
  rightWing: {
    id: "right-wing",
    name: "Right Wing",
    building: "DEF Building",
    totalSlots: 25,
  },
};

export const parkingSlots = [
  // Left Wing - Main Screen Slots
  {
    id: "LW-01",
    zone: "left-wing",
    row: 1,
    position: 1,
    status: "available",
    price: 5,
    building: "Tuwaiq",
  },
  {
    id: "LW-02",
    zone: "left-wing",
    row: 1,
    position: 2,
    status: "occupied",
    price: 5,
    building: "Tuwaiq",
  },
  {
    id: "LW-03",
    zone: "left-wing",
    row: 1,
    position: 3,
    status: "available",
    price: 5,
    building: "Tuwaiq",
  },
  {
    id: "LW-04",
    zone: "left-wing",
    row: 1,
    position: 4,
    status: "occupied",
    price: 5,
    building: "Tuwaiq",
  },
  {
    id: "LW-05",
    zone: "left-wing",
    row: 1,
    position: 5,
    status: "available",
    price: 5,
    building: "Tuwaiq",
  },

  {
    id: "LW-06",
    zone: "left-wing",
    row: 2,
    position: 1,
    status: "occupied",
    price: 5,
    building: "Tuwaiq",
  },
  {
    id: "LW-07",
    zone: "left-wing",
    row: 2,
    position: 2,
    status: "available",
    price: 5,
    building: "Tuwaiq",
  },
  {
    id: "LW-08",
    zone: "left-wing",
    row: 2,
    position: 3,
    status: "available",
    price: 5,
    building: "Tuwaiq",
  },
  {
    id: "LW-09",
    zone: "left-wing",
    row: 2,
    position: 4,
    status: "occupied",
    price: 5,
    building: "Tuwaiq",
  },
  {
    id: "LW-10",
    zone: "left-wing",
    row: 2,
    position: 5,
    status: "available",
    price: 5,
    building: "Tuwaiq",
  },

  {
    id: "LW-11",
    zone: "left-wing",
    row: 3,
    position: 1,
    status: "available",
    price: 5,
    building: "Tuwaiq",
  },
  {
    id: "LW-12",
    zone: "left-wing",
    row: 3,
    position: 2,
    status: "occupied",
    price: 5,
    building: "Tuwaiq",
  },
  {
    id: "LW-13",
    zone: "left-wing",
    row: 3,
    position: 3,
    status: "available",
    price: 5,
    building: "Tuwaiq",
  },
  {
    id: "LW-14",
    zone: "left-wing",
    row: 3,
    position: 4,
    status: "available",
    price: 5,
    building: "Tuwaiq",
  },
  {
    id: "LW-15",
    zone: "left-wing",
    row: 3,
    position: 5,
    status: "occupied",
    price: 5,
    building: "Tuwaiq",
  },

  {
    id: "LW-16",
    zone: "left-wing",
    row: 4,
    position: 1,
    status: "available",
    price: 5,
    building: "Tuwaiq",
  },
  {
    id: "LW-17",
    zone: "left-wing",
    row: 4,
    position: 2,
    status: "available",
    price: 5,
    building: "Tuwaiq",
  },
  {
    id: "LW-18",
    zone: "left-wing",
    row: 4,
    position: 3,
    status: "occupied",
    price: 5,
    building: "Tuwaiq",
  },
  {
    id: "LW-19",
    zone: "left-wing",
    row: 4,
    position: 4,
    status: "available",
    price: 5,
    building: "Tuwaiq",
  },
  {
    id: "LW-20",
    zone: "left-wing",
    row: 4,
    position: 5,
    status: "available",
    price: 5,
    building: "Tuwaiq",
  },

  // Right Wing Slots
  {
    id: "RW-01",
    zone: "right-wing",
    row: 1,
    position: 1,
    status: "occupied",
    price: 5,
    building: "DEF",
  },
  {
    id: "RW-02",
    zone: "right-wing",
    row: 1,
    position: 2,
    status: "available",
    price: 5,
    building: "DEF",
  },
  {
    id: "RW-03",
    zone: "right-wing",
    row: 1,
    position: 3,
    status: "available",
    price: 5,
    building: "DEF",
  },
  {
    id: "RW-04",
    zone: "right-wing",
    row: 1,
    position: 4,
    status: "occupied",
    price: 5,
    building: "DEF",
  },
  {
    id: "RW-05",
    zone: "right-wing",
    row: 1,
    position: 5,
    status: "available",
    price: 5,
    building: "DEF",
  },

  {
    id: "RW-06",
    zone: "right-wing",
    row: 2,
    position: 1,
    status: "available",
    price: 5,
    building: "DEF",
  },
  {
    id: "RW-07",
    zone: "right-wing",
    row: 2,
    position: 2,
    status: "occupied",
    price: 5,
    building: "DEF",
  },
  {
    id: "RW-08",
    zone: "right-wing",
    row: 2,
    position: 3,
    status: "available",
    price: 5,
    building: "DEF",
  },
  {
    id: "RW-09",
    zone: "right-wing",
    row: 2,
    position: 4,
    status: "available",
    price: 5,
    building: "DEF",
  },
  {
    id: "RW-10",
    zone: "right-wing",
    row: 2,
    position: 5,
    status: "occupied",
    price: 5,
    building: "DEF",
  },

  {
    id: "RW-11",
    zone: "right-wing",
    row: 3,
    position: 1,
    status: "available",
    price: 5,
    building: "DEF",
  },
  {
    id: "RW-12",
    zone: "right-wing",
    row: 3,
    position: 2,
    status: "available",
    price: 5,
    building: "DEF",
  },
  {
    id: "RW-13",
    zone: "right-wing",
    row: 3,
    position: 3,
    status: "occupied",
    price: 5,
    building: "DEF",
  },
  {
    id: "RW-14",
    zone: "right-wing",
    row: 3,
    position: 4,
    status: "available",
    price: 5,
    building: "DEF",
  },
  {
    id: "RW-15",
    zone: "right-wing",
    row: 3,
    position: 5,
    status: "available",
    price: 5,
    building: "DEF",
  },

  {
    id: "RW-16",
    zone: "right-wing",
    row: 4,
    position: 1,
    status: "occupied",
    price: 5,
    building: "DEF",
  },
  {
    id: "RW-17",
    zone: "right-wing",
    row: 4,
    position: 2,
    status: "available",
    price: 5,
    building: "DEF",
  },
  {
    id: "RW-18",
    zone: "right-wing",
    row: 4,
    position: 3,
    status: "available",
    price: 5,
    building: "DEF",
  },
  {
    id: "RW-19",
    zone: "right-wing",
    row: 4,
    position: 4,
    status: "occupied",
    price: 5,
    building: "DEF",
  },
  {
    id: "RW-20",
    zone: "right-wing",
    row: 4,
    position: 5,
    status: "available",
    price: 5,
    building: "DEF",
  },

  {
    id: "RW-21",
    zone: "right-wing",
    row: 5,
    position: 1,
    status: "available",
    price: 5,
    building: "DEF",
  },
  {
    id: "RW-22",
    zone: "right-wing",
    row: 5,
    position: 2,
    status: "available",
    price: 5,
    building: "DEF",
  },
  {
    id: "RW-23",
    zone: "right-wing",
    row: 5,
    position: 3,
    status: "occupied",
    price: 5,
    building: "DEF",
  },
  {
    id: "RW-24",
    zone: "right-wing",
    row: 5,
    position: 4,
    status: "available",
    price: 5,
    building: "DEF",
  },
  {
    id: "RW-25",
    zone: "right-wing",
    row: 5,
    position: 5,
    status: "available",
    price: 5,
    building: "DEF",
  },
];

// Helper functions
export const getAvailableSlots = () => {
  return parkingSlots.filter((slot) => slot.status === "available");
};

export const getOccupiedSlots = () => {
  return parkingSlots.filter((slot) => slot.status === "occupied");
};

export const getSlotsByZone = (zoneId) => {
  return parkingSlots.filter((slot) => slot.zone === zoneId);
};

export const getSlotById = (id) => {
  return parkingSlots.find((slot) => slot.id === id);
};

export const getAvailabilityStats = () => {
  const total = parkingSlots.length;
  const available = getAvailableSlots().length;
  const occupied = getOccupiedSlots().length;

  return {
    total,
    available,
    occupied,
    availabilityPercentage: ((available / total) * 100).toFixed(1),
  };
};
